searchInput
PeaksoftFrontend/Airbnb-web pull request #13
Opened 2024-12-19 21:33 UTC by Erzhan1212

2024-12-20 16:15 UTC, Aitula-svg approved these changes

2024-12-21 00:10 UTC, AziatAbd requested changes

2024-12-21 00:10 UTC, AziatAbd commented on src/components/UI/SearchInput.jsx
> +    />
добавьте ref

2024-12-21 15:45 UTC, AziatAbd requested changes

2024-12-21 15:45 UTC, AziatAbd commented on src/components/UI/SearchInput.jsx
> +    />
прочитайте что такое forwardRef и переделайте

2024-12-23 10:54 UTC, AziatAbd approved these changes

2024-12-23 10:55 UTC, merged