Admin/User UI
PeaksoftFrontend/Airbnb-web pull request #14
Opened 2024-12-24 19:33 UTC by Bilal2952

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/admin/Header.jsx
> +import React, { useState } from "react";
React кереги жок

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/admin/Header.jsx
> +  const toggleText = () => {
export кош

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/admin/Header.jsx
> +export default Header;
удалить 41 строканы

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/user/Header.jsx
> +import React from "react";
биринчи строканы удалить

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/user/Header.jsx
> +const Header = () => {
6 строкага export кош

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/user/Header.jsx
> +export default Header;
26 строканы удалить полностью

2024-12-25 00:27 UTC, Erzhan1212 commented on src/components/admin/Header.jsx
> +  const toggleText = () => {
toggle дегенди чон тамга менен жаз

2024-12-25 17:12 UTC, Erzhan1212 approved these changes

2024-12-29 11:55 UTC, AziatAbd requested changes

2024-12-29 11:55 UTC, AziatAbd commented on src/components/user/Header.jsx
> +      <StyledP>leave an ad</StyledP>
добавьте cursor poiner

2024-12-29 11:55 UTC, AziatAbd commented on src/components/admin/Header.jsx
> +  };
только компоненты начинаются с большой буквой

2024-12-29 11:55 UTC, AziatAbd commented on src/components/admin/Header.jsx
> +          )}
при нажатии на другие части сайта тоже должно закрываться

2024-12-29 11:55 UTC, AziatAbd commented on src/components/admin/Header.jsx
> +  };
пусть с маленькой буквой начнется!

2024-12-31 08:32 UTC, AziatAbd approved these changes

2024-12-31 08:32 UTC, merged