Feature/page
PeaksoftFrontend/Airbnb-web pull request #20
Opened 2024-12-28 00:37 UTC by Bilal2952

2024-12-28 02:53 UTC, Erzhan1212 reviewed
ховер иштебей экен. биринчи кара болуптурган бул ховер болгондо. эки эле цвет  болуш керек

2024-12-28 13:24 UTC, Erzhan1212 approved these changes

2024-12-31 08:40 UTC, AziatAbd requested changes

2024-12-31 08:40 UTC, AziatAbd commented on src/routes/admin/AdminPage.jsx
это разве AdminPage? Может быть UsersPage?

2024-12-31 08:40 UTC, AziatAbd commented on src/pages/admin/Page.jsx
удалите

2024-12-31 08:40 UTC, AziatAbd commented on src/components/admin/Header.jsx
почему здесь Header?

2024-12-31 08:40 UTC, AziatAbd commented on src/routes/admin/AdminPage.jsx
> +
раз вы сделали функцию удаления, добавьте модалку для подтверждения на удаление пользователя

2025-01-01 09:01 UTC, AziatAbd requested changes

2025-01-01 09:01 UTC, AziatAbd commented on src/pages/admin/UsersPage.jsx
> +            </Modal>
добавьте текст, а то не понятно что это за модалка,

2025-01-02 05:10 UTC, merged