Feature/button
PeaksoftFrontend/Airbnb-web pull request #6
Opened 2024-12-12 16:48 UTC by Aitula-svg

2024-12-12 17:52 UTC, Erzhan1212 approved these changes

2024-12-14 06:15 UTC, AziatAbd requested changes

2024-12-14 06:15 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +  with: "100%",
width не правильно написали

2024-12-14 06:15 UTC, AziatAbd commented on src/components/UI/CheckboxRadio.jsx
почему checkbox здесь?

2024-12-14 20:39 UTC, merged